"use client"

import { useMemo, useState } from "react"
import { Check, Download, FileText, MessageCircle, Printer, Search, Send, X } from "lucide-react"

type Row={id:number;name:string;roll:string;grade:string;guardian:string;phone:string;due:string;paid:number;total:number;months:number;last:string}
const seed:Row[]=[
 {id:1,name:"Ayesha Khan",roll:"2026-041",grade:"Grade 8-A",guardian:"Mr. Imran Khan",phone:"+92 300 123 4567",due:"PKR 42,500",paid:0,total:42500,months:2,last:"Never"},
 {id:2,name:"Hassan Raza",roll:"2026-078",grade:"Grade 7-B",guardian:"Mrs. Saira Raza",phone:"+92 321 987 6543",due:"PKR 28,750",paid:12500,total:41250,months:2,last:"15 Aug 2026"},
 {id:3,name:"Zainab Ahmed",roll:"2026-103",grade:"Grade 9-C",guardian:"Mr. Farhan Ahmed",phone:"+92 333 444 7788",due:"PKR 18,000",paid:0,total:18000,months:1,last:"Never"},
 {id:4,name:"Usman Ali",roll:"2026-119",grade:"Grade 6-A",guardian:"Mr. Tariq Ali",phone:"+92 322 555 0192",due:"PKR 9,250",paid:0,total:9250,months:1,last:"Never"},
 {id:5,name:"Maryam Siddiqui",roll:"2026-142",grade:"Grade 10-A",guardian:"Mrs. Nadia Siddiqui",phone:"+92 301 808 1122",due:"PKR 34,000",paid:34000,total:34000,months:0,last:"21 Aug 2026"},
]
const money=(n:number)=>`PKR ${n.toLocaleString()}`
const wa=(r:Row)=>`https://wa.me/?text=${encodeURIComponent(`Dear ${r.guardian}, this is a friendly reminder that ${r.name}'s school fee balance is ${money(r.total-r.paid)}. Please contact the school office for assistance.`)}`

export function ArrearsLedger(){
 const [rows,setRows]=useState(seed),[filter,setFilter]=useState("All Arrears"),[query,setQuery]=useState(""),[pay,setPay]=useState<Row|null>(null),[notice,setNotice]=useState<Row|null>(null),[broadcast,setBroadcast]=useState(false),[sent,setSent]=useState(false),[paid,setPaid]=useState("")
 const filtered=useMemo(()=>rows.filter(r=>(filter==="All Arrears"?r.paid<r.total:filter==="Overdue 60+"?r.months>=2:r.paid===0)&&(`${r.name} ${r.roll} ${r.guardian}`).toLowerCase().includes(query.toLowerCase())),[rows,filter,query])
 const outstanding=rows.reduce((a,r)=>a+r.total-r.paid,0), collected=rows.reduce((a,r)=>a+r.paid,0), overdue=rows.filter(r=>r.paid<r.total).length
 const savePayment=()=>{const amount=Math.max(0,Number(paid)||0);if(!pay)return;setRows(rs=>rs.map(r=>r.id===pay.id?{...r,paid:Math.min(r.total,r.paid+amount),last:"Today"}:r));setPay(null);setPaid("")}
 return <section className="arrears-workspace">
  <div className="arrears-heading"><div><div className="eyebrow">Fees / Arrears Recovery</div><h2>Fee Arrears &amp; Broadcast Ledger</h2><p>Track outstanding balances and reach families before arrears become a barrier.</p></div><button className="admin-btn admin-btn-primary" onClick={()=>setBroadcast(true)}><Send/> Broadcast to {overdue} defaulters</button></div>
  <div className="arrears-kpis"><div><span>Total outstanding</span><strong>{money(outstanding)}</strong><small>Across {overdue} active arrears</small></div><div><span>Collected this month</span><strong className="green-copy">{money(collected)}</strong><small>↑ 14.8% from July</small></div><div><span>Recovery rate</span><strong>68.4%</strong><small>Target: 75% by month end</small></div><div className="recovery-ring"><div className="ring"><b>68%</b><span>recovered</span></div><div><span>Monthly target</span><strong>On track</strong><small>PKR 42,000 to target</small></div></div></div>
  <div className="arrears-controls"><div className="filter-tabs">{["All Arrears","Overdue 60+","No Payment"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}<span>{f==="All Arrears"?overdue:f==="Overdue 60+"?2:3}</span></button>)}</div><label className="search-box"><Search/><input aria-label="Search arrears" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search student or guardian..."/></label></div>
  <div className="arrears-table-wrap"><table className="arrears-table"><thead><tr><th>Student</th><th>Guardian</th><th>Fee due</th><th>Months</th><th>Last payment</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><div className="ledger-student"><span>{r.name.split(" ").map(x=>x[0]).join("")}</span><div><b>{r.name}</b><small>{r.roll} · {r.grade}</small></div></div></td><td>{r.guardian}<small className="phone">{r.phone}</small></td><td><b className="due-amount">{money(r.total-r.paid)}</b><small>of {money(r.total)}</small></td><td><span className="month-pill">{r.months||"—"}</span></td><td className={r.last==="Never"?"muted-cell":""}>{r.last}</td><td><span className={`admin-status ${r.paid===0?"admin-status-overdue":"admin-status-pending"}`}><i/>{r.paid===0?"No payment":"Partial"}</span></td><td><div className="ledger-actions"><a className="row-action whatsapp" href={wa(r)} target="_blank" rel="noreferrer" aria-label={`WhatsApp ${r.name}`}><MessageCircle/></a><button className="row-action" onClick={()=>setPay(r)} aria-label={`Record payment for ${r.name}`}><Check/></button><button className="row-action" onClick={()=>setNotice(r)} aria-label={`Print notice for ${r.name}`}><Printer/></button></div></td></tr>)}</tbody></table></div>
  <div className="ledger-footer"><span>Showing {filtered.length} of {overdue} active arrears</span><div><button className="admin-btn admin-btn-outline" onClick={()=>window.print()}><Download/> Export ledger PDF</button><button className="admin-btn admin-btn-ghost"><FileText/> Daily reconciliation</button></div></div>
  {pay&&<div className="admin-modal-backdrop"><div className="small-modal"><button className="modal-close" onClick={()=>setPay(null)}><X/></button><div className="eyebrow">Payment entry</div><h2>Record partial payment</h2><p>Update the balance for <b>{pay.name}</b>.</p><label>Amount received<input autoFocus value={paid} onChange={e=>setPaid(e.target.value)} placeholder="e.g. 10000" inputMode="numeric"/></label><div className="modal-actions"><button className="admin-btn admin-btn-outline" onClick={()=>setPay(null)}>Cancel</button><button className="admin-btn admin-btn-primary" onClick={savePayment}>Save payment</button></div></div></div>}
  {notice&&<div className="admin-modal-backdrop"><div className="notice-modal"><div className="notice-actions"><button className="admin-btn admin-btn-outline" onClick={()=>window.print()}><Printer/> Print notice</button><button className="modal-close" onClick={()=>setNotice(null)}><X/></button></div><div className="eyebrow">Confidential fee notice</div><h2>Payment reminder</h2><p>Dear {notice.guardian},</p><p>This is a reminder that <b>{notice.name}</b> ({notice.roll}) has an outstanding school fee balance of <b>{money(notice.total-notice.paid)}</b>.</p><p>Please contact the accounts office to arrange payment or a support plan.</p><div className="notice-sign">The Smart Scholars Academy<br/><small>Accounts Office · Lahore Campus</small></div></div></div>}
  {broadcast&&<div className="admin-modal-backdrop"><div className="broadcast-modal"><button className="modal-close" onClick={()=>{setBroadcast(false);setSent(false)}}><X/></button>{sent?<div className="broadcast-success"><div className="success-icon"><Check/></div><h2>Broadcast queued</h2><p>{overdue} personalized reminders are ready to send on WhatsApp.</p><button className="admin-btn admin-btn-primary" onClick={()=>{setBroadcast(false);setSent(false)}}>Done</button></div>:<><div className="eyebrow">WhatsApp Broadcast</div><h2>Reach families in one click</h2><p>Choose a message template. Every reminder includes the student name and live balance.</p><div className="broadcast-template active"><b>Friendly payment reminder</b><span>Warm, helpful, and best for first contact.</span></div><div className="broadcast-template"><b>Overdue notice</b><span>Clear and direct for balances over 60 days.</span></div><div className="broadcast-preview"><small>LIVE PREVIEW</small><p>Dear {seed[0].guardian}, this is a friendly reminder that {seed[0].name}&apos;s school fee balance is {money(seed[0].total)}.</p></div><div className="modal-actions"><button className="admin-btn admin-btn-outline" onClick={()=>setBroadcast(false)}>Cancel</button><button className="admin-btn admin-btn-primary" onClick={()=>setSent(true)}><Send/> Queue {overdue} reminders</button></div></>}</div></div>}
 </section>
}
