"use client"

import { useMemo, useState } from "react"
import { ArrowDownLeft, ArrowUpRight, Banknote, Calculator, Check, ChevronDown, FileText, Image as ImageIcon, MessageCircle, Plus, Printer, ReceiptText, Search, Upload, Wallet, X } from "lucide-react"

const initialTransactions = [
  { id: "EXP-2401", date: "24 Aug 2026", category: "Utilities", description: "LESCO electricity bill — August", vendor: "LESCO", amount: -28500, status: "Cleared", receipt: true },
  { id: "INC-0824", date: "24 Aug 2026", category: "Fee collection", description: "Class 5-A monthly fees", vendor: "Batch deposit", amount: 156000, status: "Cleared", receipt: false },
  { id: "EXP-2399", date: "23 Aug 2026", category: "Stationery", description: "Exercise books and exam paper", vendor: "Punjab Books", amount: -12400, status: "Cleared", receipt: true },
  { id: "PAY-0823", date: "23 Aug 2026", category: "Payroll", description: "August salary sheet — 18 staff", vendor: "Payroll", amount: -642000, status: "Scheduled", receipt: false },
  { id: "EXP-2397", date: "22 Aug 2026", category: "Maintenance", description: "Science lab tap repair", vendor: "A. Rehman Works", amount: -6800, status: "Cleared", receipt: true },
]

const money = (amount: number) => `${amount < 0 ? "−" : ""}PKR ${Math.abs(amount).toLocaleString("en-PK")}`

export function FinanceWorkspace() {
  const [transactions, setTransactions] = useState(initialTransactions)
  const [tab, setTab] = useState<"ledger" | "payroll" | "cash">("ledger")
  const [modal, setModal] = useState<"expense" | "payroll" | "cash" | null>(null)
  const [query, setQuery] = useState("")
  const [category, setCategory] = useState("All categories")
  const [toast, setToast] = useState("")
  const [expense, setExpense] = useState({ description: "", vendor: "", amount: "", category: "Utilities" })
  const [paid, setPaid] = useState<string[]>([])

  const filtered = useMemo(() => transactions.filter((row) => `${row.description} ${row.vendor} ${row.category}`.toLowerCase().includes(query.toLowerCase()) && (category === "All categories" || row.category === category)), [transactions, query, category])
  const totalIncome = transactions.filter((x) => x.amount > 0).reduce((a, x) => a + x.amount, 0)
  const totalExpense = Math.abs(transactions.filter((x) => x.amount < 0).reduce((a, x) => a + x.amount, 0))
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2800) }

  const addExpense = () => {
    if (!expense.description || !expense.vendor || !expense.amount) return
    setTransactions((rows) => [{ id: `EXP-${2402 + rows.length}`, date: "Today", category: expense.category, description: expense.description, vendor: expense.vendor, amount: -Number(expense.amount), status: "Pending", receipt: true }, ...rows])
    setModal(null); setExpense({ description: "", vendor: "", amount: "", category: "Utilities" }); notify("Expense voucher saved to the ledger")
  }

  return <main className="finance-page">
    <header className="finance-page-header"><div><span className="finance-eyebrow">FINANCE CONTROL CENTER</span><h1>School Finance & Operations</h1><p>Track cashflow, expenses, payroll, and petty cash from one place.</p></div><div className="finance-header-actions"><button className="finance-btn secondary" onClick={() => window.print()}><Printer /> Print report</button><button className="finance-btn primary" onClick={() => setModal("expense")}><Plus /> Add expense voucher</button></div></header>
    {toast && <div className="finance-toast" role="status"><Check /> {toast}</div>}
    <section className="finance-kpis"><div><span>Available balance</span><strong>PKR 2,486,320</strong><small className="positive"><ArrowUpRight /> 12.8% vs last month</small></div><div><span>Income this month</span><strong className="income">{money(totalIncome)}</strong><small>24 fee deposits posted</small></div><div><span>Expenses this month</span><strong className="expense">{money(totalExpense)}</strong><small>8 vouchers · 2 pending</small></div><div><span>Petty cash</span><strong>PKR 38,450</strong><small className="positive">Within daily limit</small></div></section>
    <nav className="finance-tabs" aria-label="Finance sections"><button className={tab === "ledger" ? "active" : ""} onClick={() => setTab("ledger")}><ReceiptText /> Transaction ledger</button><button className={tab === "payroll" ? "active" : ""} onClick={() => setTab("payroll")}><Banknote /> Salary sheet</button><button className={tab === "cash" ? "active" : ""} onClick={() => setTab("cash")}><Wallet /> Petty cash closing</button></nav>
    {tab === "ledger" && <section className="finance-card"><div className="finance-card-heading"><div><span className="finance-eyebrow">AUGUST 2026</span><h2>Income & expense ledger</h2></div><button className="finance-btn secondary" onClick={() => notify("CSV export prepared")}>Export CSV</button></div><div className="finance-filters"><label><Search /><input placeholder="Search transactions..." value={query} onChange={(e) => setQuery(e.target.value)} /></label><select value={category} onChange={(e) => setCategory(e.target.value)}><option>All categories</option><option>Utilities</option><option>Stationery</option><option>Maintenance</option><option>Payroll</option><option>Fee collection</option></select><span>{filtered.length} entries</span></div><div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Date</th><th>Transaction</th><th>Category</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td>{row.date}<small>{row.id}</small></td><td><b>{row.description}</b><small>{row.vendor} {row.receipt && "· Receipt attached"}</small></td><td><span className="category-pill">{row.category}</span></td><td className={row.amount < 0 ? "amount-expense" : "amount-income"}>{money(row.amount)}</td><td><span className={`finance-status ${row.status.toLowerCase()}`}>{row.status}</span></td><td><button className="table-action" onClick={() => notify(row.receipt ? `Receipt preview opened for ${row.id}` : `Details opened for ${row.id}`)}>{row.receipt ? <ImageIcon /> : <FileText />}</button></td></tr>)}</tbody></table></div><footer className="finance-card-footer"><span>Showing {filtered.length} of {transactions.length} transactions</span><span><Calculator /> Reconciled 24 Aug 2026</span></footer></section>}
    {tab === "payroll" && <section className="finance-card payroll-sheet"><div className="finance-card-heading"><div><span className="finance-eyebrow">AUGUST 2026 · 18 STAFF</span><h2>Salary sheet & disbursal</h2><p>Review attendance-adjusted payroll before releasing salaries.</p></div><button className="finance-btn primary" onClick={() => setModal("payroll")}><Banknote /> Process payroll</button></div><div className="payroll-summary"><div><span>Gross payroll</span><strong>PKR 742,000</strong></div><div><span>Deductions</span><strong>PKR 100,000</strong></div><div><span>Net payable</span><strong className="income">PKR 642,000</strong></div></div><div className="salary-list">{[["Sir Bilal", "Mathematics", "PKR 52,000"], ["Miss Ayesha", "Science", "PKR 48,000"], ["Sir Hamza", "English", "PKR 44,000"], ["Miss Hina", "Urdu", "PKR 41,000"]].map(([name, role, amount]) => <div key={name}><span className="staff-avatar">{name.split(" ").map((x) => x[0]).join("")}</span><div><b>{name}</b><small>{role} · 22 days present</small></div><strong>{amount}</strong><span className="finance-status scheduled">Ready</span><button className="table-action" onClick={() => { setPaid((p) => [...p, name]); notify(`Pay-slip generated for ${name}`) }}><FileText /></button></div>)}</div></section>}
    {tab === "cash" && <section className="finance-card cash-closing"><div className="finance-card-heading"><div><span className="finance-eyebrow">24 AUGUST 2026 · DAILY CLOSE</span><h2>Petty cash reconciliation</h2><p>Count, reconcile, and sign off the day before closing.</p></div><button className="finance-btn primary" onClick={() => setModal("cash")}><Check /> Close day</button></div><div className="cash-grid"><div><span>Opening float</span><strong>PKR 50,000</strong></div><div><span>Cash expenses</span><strong className="expense">− PKR 11,550</strong></div><div><span>Expected closing</span><strong>PKR 38,450</strong></div><div><span>Counted cash</span><strong className="income">PKR 38,450</strong><small className="positive">No variance</small></div></div><div className="cash-receipts"><h3>Today&apos;s vouchers</h3>{["Tea & water for staff meeting", "Photocopies — Class 8-B worksheets", "Local transport — bank deposit"].map((item, i) => <div key={item}><span><ReceiptText /> {item}</span><strong>PKR {[4200, 3850, 3500][i].toLocaleString()}</strong><span className="finance-status cleared">Verified</span></div>)}</div></section>}
    {modal === "expense" && <div className="finance-modal-backdrop"><div className="finance-modal"><button className="modal-close" onClick={() => setModal(null)} aria-label="Close"><X /></button><span className="finance-eyebrow">NEW VOUCHER</span><h2>Add expense voucher</h2><p>Record a school expense and attach its receipt for audit readiness.</p><label>Description<input value={expense.description} onChange={(e) => setExpense({ ...expense, description: e.target.value })} placeholder="e.g. Classroom whiteboard markers" /></label><label>Vendor<input value={expense.vendor} onChange={(e) => setExpense({ ...expense, vendor: e.target.value })} placeholder="e.g. Punjab Books" /></label><div className="finance-form-row"><label>Category<select value={expense.category} onChange={(e) => setExpense({ ...expense, category: e.target.value })}><option>Utilities</option><option>Stationery</option><option>Maintenance</option><option>Transport</option></select></label><label>Amount (PKR)<input type="number" value={expense.amount} onChange={(e) => setExpense({ ...expense, amount: e.target.value })} placeholder="0" /></label></div><button className="receipt-upload" onClick={() => notify("Receipt attachment ready") }><Upload /> Attach receipt image or PDF</button><div className="modal-actions"><button className="finance-btn secondary" onClick={() => setModal(null)}>Cancel</button><button className="finance-btn primary" onClick={addExpense}>Save voucher</button></div></div></div>}
    {modal === "payroll" && <div className="finance-modal-backdrop"><div className="finance-modal"><button className="modal-close" onClick={() => setModal(null)} aria-label="Close"><X /></button><span className="finance-eyebrow">FINAL REVIEW</span><h2>Process August payroll?</h2><p>18 salary slips will be generated for a net disbursal of PKR 642,000. Each staff member will receive a personal pay-slip.</p><div className="payroll-confirm"><Check /> Attendance checked · deductions applied · bank file ready</div><div className="modal-actions"><button className="finance-btn secondary" onClick={() => setModal(null)}>Review later</button><button className="finance-btn primary" onClick={() => { setModal(null); notify("Payroll approved — pay-slips are ready") }}>Approve payroll</button></div></div></div>}
    {modal === "cash" && <div className="finance-modal-backdrop"><div className="finance-modal"><button className="modal-close" onClick={() => setModal(null)} aria-label="Close"><X /></button><span className="finance-eyebrow">DAILY SIGN-OFF</span><h2>Close petty cash day</h2><p>Confirm counted cash of PKR 38,450 matches the expected closing balance.</p><label>Signed off by<input defaultValue="Aamir Khan · Admin" /></label><div className="payroll-confirm"><Check /> No variance detected</div><div className="modal-actions"><button className="finance-btn secondary" onClick={() => setModal(null)}>Cancel</button><button className="finance-btn primary" onClick={() => { setModal(null); notify("Petty cash closed and reconciliation saved") }}>Close day</button></div></div></div>}
  </main>
}
