export interface ProvinceData {
  province: string
  cities: string[]
}

export const PAKISTAN_LOCATIONS: Record<string, string[]> = {
  'Sindh': [
    'Karachi',
    'Hyderabad',
    'Sukkur',
    'Larkana',
    'Nawabshah (Shaheed Benazirabad)',
    'Mirpur Khas',
    'Jacobabad',
    'Shikarpur',
    'Khairpur',
    'Dadu',
    'Thatta',
    'Badin',
    'Ghotki',
    'Tando Adam',
    'Tando Allahyar',
    'Tando Muhammad Khan',
    'Umerkot',
    'Kotri',
    'Jamshoro',
    'Kashmore',
    'Sanghar',
    'Moro',
    'Sehwan',
    'Shahdadkot',
    'Kandhkot',
    'Matiari',
    'Kambar',
    'Mirpur Mathelo',
    'Daharki',
    'Naushahro Feroze',
    'Digri',
    'Mithi',
    'Islamkot',
    'Gambat',
    'Ranipur',
    'Other / Rural Sindh',
  ],
  'Punjab': [
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Gujranwala',
    'Multan',
    'Sialkot',
    'Bahawalpur',
    'Sargodha',
    'Sahiwal',
    'Sheikhupura',
    'Jhang',
    'Rahim Yar Khan',
    'Gujrat',
    'Kasur',
    'Okara',
    'Chiniot',
    'Kamoke',
    'Hafizabad',
    'Mandi Bahauddin',
    'Dera Ghazi Khan',
    'Muzaffargarh',
    'Khanewal',
    'Vehari',
    'Bahawalnagar',
    'Chakwal',
    'Jhelum',
    'Mianwali',
    'Attock',
    'Pakpattan',
    'Toba Tek Singh',
    'Murree',
    'Wazirabad',
    'Layyah',
    'Lodhran',
    'Bhakkar',
    'Kot Addu',
    'Burewala',
    'Gojra',
    'Bhalwal',
    'Chichawatni',
    'Pattoki',
    'Chunian',
    'Jalalpur Jattan',
    'Kharian',
    'Taxila',
    'Wah Cantt',
    'Ahmedpur East',
    'Daska',
    'Samundri',
    'Other / Rural Punjab',
  ],
  'Khyber Pakhtunkhwa (KPK)': [
    'Peshawar',
    'Mardan',
    'Mingora (Swat)',
    'Abbottabad',
    'Kohat',
    'Dera Ismail Khan',
    'Mansehra',
    'Swabi',
    'Nowshera',
    'Charsadda',
    'Haripur',
    'Bannu',
    'Batkhela',
    'Karak',
    'Malakand',
    'Chitral',
    'Timergara (Lower Dir)',
    'Upper Dir',
    'Hangu',
    'Risalpur',
    'Shabqadar',
    'Tank',
    'Parachinar',
    'Landi Kotal',
    'Jamrud',
    'Tangi',
    'Topi',
    'Buner',
    'Shangla',
    'Other / Rural KPK',
  ],
  'Balochistan': [
    'Quetta',
    'Turbat',
    'Khuzdar',
    'Hub',
    'Chaman',
    'Gwadar',
    'Sibi',
    'Dera Murad Jamali',
    'Zhob',
    'Loralai',
    'Pishin',
    'Nushki',
    'Mastung',
    'Kalat',
    'Kharan',
    'Kohlu',
    'Panjgur',
    'Dera Bugti',
    'Ziarat',
    'Usta Mohammad',
    'Qila Saifullah',
    'Qila Abdullah',
    'Jaffarabad',
    'Lasbela',
    'Pasni',
    'Ormara',
    'Other / Rural Balochistan',
  ],
  'Islamabad Capital Territory (ICT)': [
    'Islamabad (Capital)',
    'Bara Kahu',
    'Tarnol',
    'Sihala',
    'Rawat',
    'Golra Sharif',
    'Nilore',
    'Shah Allah Ditta',
    'Chak Shahzad',
    'Tarlai Kalan',
    'Other / Rural ICT',
  ],
  'Azad Jammu & Kashmir (AJK)': [
    'Muzaffarabad',
    'Mirpur',
    'Rawalakot',
    'Kotli',
    'Bhimber',
    'Bagh',
    'Pallandri (Sudhanoti)',
    'Haveli',
    'Hattian Bala',
    'Athmuqam (Neelum Valley)',
    'Dadyal',
    'Other / Rural AJK',
  ],
  'Gilgit-Baltistan (GB)': [
    'Gilgit',
    'Skardu',
    'Hunza (Karimabad)',
    'Chilas (Diamer)',
    'Ghizer',
    'Astore',
    'Shigar',
    'Kharmang',
    'Nagar',
    'Gupis',
    'Aliabad',
    'Passu',
    'Other / Rural GB',
  ],
}

export const PROVINCES = Object.keys(PAKISTAN_LOCATIONS)
